version: '3.8'

services:
  # Flask application service
  flask-app:
    build: .
    container_name: todo-flask-app
    ports:
      - "8000:5000"
    environment:
      - FLASK_ENV=production
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb
    networks:
      - todo-network
    restart: unless-stopped

  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: todo-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=camp2016
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo-network
    restart: unless-stopped

# Named volumes for data persistence
volumes:
  mongodb_data:
    driver: local

# Custom network for service communication
networks:
  todo-network:
    driver: bridge